//
// InquiryAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import IBCommon
import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
open class InquiryAPI {
    /**
     Approve Confirm Inquiry
     - POST /ext-payment/inquiry/approve/confirm/1.0
     - Approve Confirm Inquiry
     - parameter initTransConfirmDto: (body)  
     - returns: RequestBuilder<ResultConfirmTransRecallResDto> 
     */
    open class func approveConfirmInquiry(initTransConfirmDto: InitTransConfirmDto) -> RequestBuilder<ResultConfirmTransRecallResDto> {
        let localVariablePath = "/ext-payment/inquiry/approve/confirm/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: initTransConfirmDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Approve Inquiry
     - POST /ext-payment/inquiry/approve/1.0
     - Approve Inquiry
     - parameter approveInquiryRequestDto: (body)  
     - returns: RequestBuilder<ResultInitTransactionResObject> 
     */
    open class func approveInquiry(approveInquiryRequestDto: ApproveInquiryRequestDto) -> RequestBuilder<ResultInitTransactionResObject> {
        let localVariablePath = "/ext-payment/inquiry/approve/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: approveInquiryRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Create bulk child transfer inquiry
     - POST /ext-payment/inquiry/bulk-child/create/1.0
     - Create bulk child transfer inquiry
     - parameter createTransferInquiryRequest: (body)  
     - returns: RequestBuilder<ResultCreateBulkChildTransferInquiryResponse> 
     */
    open class func createBulkChildTransferInquiry(createTransferInquiryRequest: CreateTransferInquiryRequest) -> RequestBuilder<ResultCreateBulkChildTransferInquiryResponse> {
        let localVariablePath = "/ext-payment/inquiry/bulk-child/create/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTransferInquiryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Create bulk transfer inquiry
     - POST /ext-payment/inquiry/bulk/create/1.0
     - Create bulk transfer inquiry
     - parameter createTransferInquiryRequest: (body)  
     - returns: RequestBuilder<ResultCreateBulkTransferInquiryResponse> 
     */
    open class func createBulkTransferInquiry(createTransferInquiryRequest: CreateTransferInquiryRequest) -> RequestBuilder<ResultCreateBulkTransferInquiryResponse> {
        let localVariablePath = "/ext-payment/inquiry/bulk/create/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTransferInquiryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Create fund transfer inquiry
     - POST /ext-payment/inquiry/transfer/create/1.0
     - Create fund transfer inquiry
     - parameter createTransferInquiryRequest: (body)  
     - returns: RequestBuilder<ResultCreateFundTransferInquiryResponse> 
     */
    open class func createFundTransferInquiry(createTransferInquiryRequest: CreateTransferInquiryRequest) -> RequestBuilder<ResultCreateFundTransferInquiryResponse> {
        let localVariablePath = "/ext-payment/inquiry/transfer/create/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTransferInquiryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Deposit - get category list 
     - POST /masterdata/par/category-by-type/list/1.0
     - Danh sách Category theo Type
     - parameter categoryRequestDto: (body)  
     - returns: RequestBuilder<ResultListCategoryResponseDto> 
     */
    open class func getCategoriesByType(categoryRequestDto: CategoryRequestDto) -> RequestBuilder<ResultListCategoryResponseDto> {
        let localVariablePath = "/masterdata/par/category-by-type/list/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: categoryRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Inquiry Bulk (Checker)
     - POST /ext-payment/inquiry/bulk/pending-approval/detail/1.0
     - Get Detail Inquiry Bulk (Checker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryBulkDetailResponseDto> 
     */
    open class func getDetailInquiryBulkChecker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryBulkDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk/pending-approval/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Inquiry Bulk Child (Checker)
     - POST /ext-payment/inquiry/bulk-child/pending-approval/detail/1.0
     - Get Detail Inquiry Bulk Child (Checker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryBulkChildDetailResponseDto> 
     */
    open class func getDetailInquiryBulkChildChecker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryBulkChildDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk-child/pending-approval/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Inquiry Bulk Child (Maker)
     - POST /ext-payment/inquiry/bulk-child/detail/1.0
     - Get Detail Inquiry Bulk Child (Maker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryBulkChildDetailResponseDto> 
     */
    open class func getDetailInquiryBulkChildMaker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryBulkChildDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk-child/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Inquiry Bulk (Maker)
     - POST /ext-payment/inquiry/bulk/detail/1.0
     - Get Detail Inquiry Bulk (Maker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryBulkDetailResponseDto> 
     */
    open class func getDetailInquiryBulkMaker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryBulkDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Payment Inquiry (Checker)
     - POST /ext-payment/inquiry/transfer/pending-approval/detail/1.0
     - Get Detail Payment Inquiry (Checker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryDetailResponseDto> 
     */
    open class func getDetailInquiryChecker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/transfer/pending-approval/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Detail Payment Inquiry (Maker)
     - POST /ext-payment/inquiry/transfer/detail/1.0
     - Get Detail Payment Inquiry (Maker)
     - parameter txnInquiryDetailRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnInquiryDetailResponseDto> 
     */
    open class func getDetailInquiryMaker(txnInquiryDetailRequestDto: TxnInquiryDetailRequestDto) -> RequestBuilder<ResultTxnInquiryDetailResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/transfer/detail/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryDetailRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get List Payment Inquiry Bulk
     - POST /ext-payment/inquiry/bulk/search/1.0
     - Get List Payment Inquiry Bulk
     - parameter txnInquiryListTransferRequestDto: (body)  
     - returns: RequestBuilder<ResultListTxnInquiryListBulkResponseDto> 
     */
    open class func getListInquiryListBulk(txnInquiryListTransferRequestDto: TxnInquiryListTransferRequestDto) -> RequestBuilder<ResultListTxnInquiryListBulkResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk/search/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListTransferRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get List Payment Inquiry Bulk Child
     - POST /ext-payment/inquiry/bulk-child/search/1.0
     - Get List Payment Inquiry Bulk
     - parameter txnInquiryListTransferRequestDto: (body)  
     - returns: RequestBuilder<ResultListTxnInquiryListBulkResponseDto> 
     */
    open class func getListInquiryListBulkChild(txnInquiryListTransferRequestDto: TxnInquiryListTransferRequestDto) -> RequestBuilder<ResultListTxnInquiryListBulkResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/bulk-child/search/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListTransferRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get List Payment Inquiry Checker
     - POST /ext-payment/inquiry/pending-approval/list/1.0
     - Get List Payment Inquiry Checker
     - parameter txnInquiryListRequestDto: (body)  
     - returns: RequestBuilder<ResultListTxnInquiryResponseDto> 
     */
    open class func getListInquiryListChecker(txnInquiryListRequestDto: TxnInquiryListRequestDto) -> RequestBuilder<ResultListTxnInquiryResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/pending-approval/list/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get List Payment Inquiry Maker
     - POST /ext-payment/inquiry/list/1.0
     - Get List Payment Inquiry Maker
     - parameter txnInquiryListRequestDto: (body)  
     - returns: RequestBuilder<ResultListTxnInquiryResponseDto> 
     */
    open class func getListInquiryListMaker(txnInquiryListRequestDto: TxnInquiryListRequestDto) -> RequestBuilder<ResultListTxnInquiryResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/list/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get List Payment Inquiry Transfer
     - POST /ext-payment/inquiry/transfer/search/1.0
     - Get List Payment Inquiry Transfer
     - parameter txnInquiryListTransferRequestDto: (body)  
     - returns: RequestBuilder<ResultListTxnInquiryListTransferResponseDto> 
     */
    open class func getListInquiryListTransfer(txnInquiryListTransferRequestDto: TxnInquiryListTransferRequestDto) -> RequestBuilder<ResultListTxnInquiryListTransferResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/transfer/search/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListTransferRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Print Payment Inquiry
     - POST /ext-payment/inquiry/print/1.0
     - Get Print Payment Inquiry
     - parameter txnPrintRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnPrintResponseDto> 
     */
    open class func getPrintInquiryMaker(txnPrintRequestDto: TxnPrintRequestDto) -> RequestBuilder<ResultTxnPrintResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/print/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnPrintRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Get Report Payment Inquiry
     - POST /ext-payment/inquiry/export/1.0
     - Get Report Payment Inquiry
     - parameter txnInquiryListRequestDto: (body)  
     - returns: RequestBuilder<ResultTxnPrintResponseDto> 
     */
    open class func getReportInquiryMaker(txnInquiryListRequestDto: TxnInquiryListRequestDto) -> RequestBuilder<ResultTxnPrintResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/export/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: txnInquiryListRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Init Confirm Inquiry
     - POST /ext-payment/inquiry/init/confirm/1.0
     - Init Confirm Inquiry
     - parameter initTransConfirmDto: (body)  
     - returns: RequestBuilder<ResultInitConfirmInquiryResponseDto> 
     */
    open class func initConfirmInquiry(initTransConfirmDto: InitTransConfirmDto) -> RequestBuilder<ResultInitConfirmInquiryResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/init/confirm/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: initTransConfirmDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Init Inquiry
     - POST /ext-payment/inquiry/init/1.0
     - Init Inquiry
     - parameter createTransferInquiryRequestDto: (body)  
     - returns: RequestBuilder<ResultInitTransactionResObject> 
     */
    open class func initInquiry(createTransferInquiryRequestDto: CreateTransferInquiryRequestDto) -> RequestBuilder<ResultInitTransactionResObject> {
        let localVariablePath = "/ext-payment/inquiry/init/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTransferInquiryRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Reject List payment inquiry Checker
     - POST /ext-payment/inquiry/reject/1.0
     - Reject List payment inquiry Checker
     - parameter rejectTransactionDTO: (body)  
     - returns: RequestBuilder<ResultConfirmTransRecallResDto> 
     */
    open class func rejectPaymentInquiry(rejectTransactionDTO: RejectTransactionDTO) -> RequestBuilder<ResultConfirmTransRecallResDto> {
        let localVariablePath = "/ext-payment/inquiry/reject/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rejectTransactionDTO)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
    /**
     Validate Inquiry
     - POST /ext-payment/inquiry/validate/1.0
     - Validate Inquiry
     - parameter validateInquiryRequestDto: (body)  
     - returns: RequestBuilder<ResultValidateInquiryResponseDto> 
     */
    open class func validateInquiry(validateInquiryRequestDto: ValidateInquiryRequestDto) -> RequestBuilder<ResultValidateInquiryResponseDto> {
        let localVariablePath = "/ext-payment/inquiry/validate/1.0"
        let localVariableURLString = OpenAPIClientAPI.pathExtension("InquiryAPI") + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: validateInquiryRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders) 
        return RequestBuilder.init(method: "POST", path: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
