//
// ApproveInquiryRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApproveInquiryRequestDto: Codable, Responseable, JSONEncodable, Hashable {

    public var txnIds: [String]

    public init(txnIds: [String]) {
        self.txnIds = txnIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txnIds
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        txnIds = container.decodeIfPresent(.txnIds) ?? .empty
       
    }
    
}

extension ApproveInquiryRequestDto: Emptyable {
    public static var empty: ApproveInquiryRequestDto {
        return .init(txnIds: .empty)
    }
}
