//
// CategoryRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryRequestDto: Codable, Responseable, JSONEncodable, Hashable {

    public var categoryType: [String]

    public init(categoryType: [String]) {
        self.categoryType = categoryType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryType
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        categoryType = container.decodeIfPresent(.categoryType) ?? .empty
       
    }
    
}

extension CategoryRequestDto: Emptyable {
    public static var empty: CategoryRequestDto {
        return .init(categoryType: .empty)
    }
}
