//
// InitTransConfirmDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InitTransConfirmDto: Codable, Responseable, JSONEncodable, Hashable {

    static let confirmValueRule = StringRule(minLength: 0, maxLength: 50, pattern: nil)
    public var transKey: String
    public var confirmValue: String?

    public init(transKey: String, confirmValue: String? = nil) {
        self.transKey = transKey
        self.confirmValue = confirmValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transKey
        case confirmValue
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        transKey = container.decodeIfPresent(.transKey) ?? .empty
        confirmValue = container.decodeIfPresent(.confirmValue)
       
    }
    
}

extension InitTransConfirmDto: Emptyable {
    public static var empty: InitTransConfirmDto {
        return .init(transKey: .empty, confirmValue: nil)
    }
}
