//
// InitTransactionResObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Data */
public struct InitTransactionResObject: Codable, Responseable, JSONEncodable, Hashable {

    public var transKey: String?
    public var transaction: AnyCodable?
    public var requireAuth: Bool?
    public var transAuth: TransAuth?
    public var confirmUrl: String?

    public init(transKey: String? = nil, transaction: AnyCodable? = nil, requireAuth: Bool? = nil, transAuth: TransAuth? = nil, confirmUrl: String? = nil) {
        self.transKey = transKey
        self.transaction = transaction
        self.requireAuth = requireAuth
        self.transAuth = transAuth
        self.confirmUrl = confirmUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transKey
        case transaction
        case requireAuth
        case transAuth
        case confirmUrl
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        transKey = container.decodeIfPresent(.transKey)
        transaction = container.decodeIfPresent(.transaction)
        requireAuth = container.decodeIfPresent(.requireAuth)
        transAuth = container.decodeIfPresent(.transAuth)
        confirmUrl = container.decodeIfPresent(.confirmUrl)
       
    }
    
}

extension InitTransactionResObject: Emptyable {
    public static var empty: InitTransactionResObject {
        return .init(transKey: nil, transaction: nil, requireAuth: nil, transAuth: nil, confirmUrl: nil)
    }
}
