//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Order: Codable, Responseable, JSONEncodable, Hashable {

    public var field: String?
    public var direction: String?

    public init(field: String? = nil, direction: String? = nil) {
        self.field = field
        self.direction = direction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case direction
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        field = container.decodeIfPresent(.field)
        direction = container.decodeIfPresent(.direction)
       
    }
    
}

extension Order: Emptyable {
    public static var empty: Order {
        return .init(field: nil, direction: nil)
    }
}
