//
// QrTransGroupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QrTransGroupDto: Codable, Responseable, JSONEncodable, Hashable {

    /** CCY */
    public var ccy: String?
    /** amount */
    public var amount: String?
    /** amountText */
    public var amountText: String?
    /** total */
    public var total: String?

    public init(ccy: String? = nil, amount: String? = nil, amountText: String? = nil, total: String? = nil) {
        self.ccy = ccy
        self.amount = amount
        self.amountText = amountText
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ccy
        case amount
        case amountText
        case total
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        ccy = container.decodeIfPresent(.ccy)
        amount = container.decodeIfPresent(.amount)
        amountText = container.decodeIfPresent(.amountText)
        total = container.decodeIfPresent(.total)
       
    }
    
}

extension QrTransGroupDto: Emptyable {
    public static var empty: QrTransGroupDto {
        return .init(ccy: nil, amount: nil, amountText: nil, total: nil)
    }
}
