//
// TransactionInquiry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionInquiry: Codable, Responseable, JSONEncodable, Hashable {

    public var orgTxnId: String?

    public init(orgTxnId: String? = nil) {
        self.orgTxnId = orgTxnId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgTxnId
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        orgTxnId = container.decodeIfPresent(.orgTxnId)
       
    }
    
}

extension TransactionInquiry: Emptyable {
    public static var empty: TransactionInquiry {
        return .init(orgTxnId: nil)
    }
}
