//
// TxnInquiryListTransferResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List data */
public struct TxnInquiryListTransferResponseDto: Codable, Responseable, JSONEncodable, Hashable {

    public var id: String?
    public var benBankNameShort: String?
    public var benAccNo: String?
    public var benName: String?
    public var txnType: String?
    public var cardNo: String?
    public var effDate: String?
    public var status: String?
    public var amount: Double?
    public var ccy: String?
    public var benId: String?

    public init(id: String? = nil, benBankNameShort: String? = nil, benAccNo: String? = nil, benName: String? = nil, txnType: String? = nil, cardNo: String? = nil, effDate: String? = nil, status: String? = nil, amount: Double? = nil, ccy: String? = nil, benId: String? = nil) {
        self.id = id
        self.benBankNameShort = benBankNameShort
        self.benAccNo = benAccNo
        self.benName = benName
        self.txnType = txnType
        self.cardNo = cardNo
        self.effDate = effDate
        self.status = status
        self.amount = amount
        self.ccy = ccy
        self.benId = benId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case benBankNameShort
        case benAccNo
        case benName
        case txnType
        case cardNo
        case effDate
        case status
        case amount
        case ccy
        case benId
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = container.decodeIfPresent(.id)
        benBankNameShort = container.decodeIfPresent(.benBankNameShort)
        benAccNo = container.decodeIfPresent(.benAccNo)
        benName = container.decodeIfPresent(.benName)
        txnType = container.decodeIfPresent(.txnType)
        cardNo = container.decodeIfPresent(.cardNo)
        effDate = container.decodeIfPresent(.effDate)
        status = container.decodeIfPresent(.status)
        amount = container.decodeIfPresent(.amount)
        ccy = container.decodeIfPresent(.ccy)
        benId = container.decodeIfPresent(.benId)
       
    }
    
}

extension TxnInquiryListTransferResponseDto: Emptyable {
    public static var empty: TxnInquiryListTransferResponseDto {
        return .init(id: nil, benBankNameShort: nil, benAccNo: nil, benName: nil, txnType: nil, cardNo: nil, effDate: nil, status: nil, amount: nil, ccy: nil, benId: nil)
    }
}
