//
// TxnPrintResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Data */
public struct TxnPrintResponseDto: Codable, Responseable, JSONEncodable, Hashable {

    public var url: String?

    public init(url: String? = nil) {
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        url = container.decodeIfPresent(.url)
       
    }
    
}

extension TxnPrintResponseDto: Emptyable {
    public static var empty: TxnPrintResponseDto {
        return .init(url: nil)
    }
}
