//
// ValidateInquiryResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Data */
public struct ValidateInquiryResponseDto: Codable, Responseable, JSONEncodable, Hashable {

    public var feeTotal: Double?
    public var id: String?
    public var validateInquiryResponse: String?

    public init(feeTotal: Double? = nil, id: String? = nil, validateInquiryResponse: String? = nil) {
        self.feeTotal = feeTotal
        self.id = id
        self.validateInquiryResponse = validateInquiryResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feeTotal
        case id
        case validateInquiryResponse
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        feeTotal = container.decodeIfPresent(.feeTotal)
        id = container.decodeIfPresent(.id)
        validateInquiryResponse = container.decodeIfPresent(.validateInquiryResponse)
       
    }
    
}

extension ValidateInquiryResponseDto: Emptyable {
    public static var empty: ValidateInquiryResponseDto {
        return .init(feeTotal: nil, id: nil, validateInquiryResponse: nil)
    }
}
