//
// ValidateInquiryRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import IBCommon
import IBFoundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidateInquiryRequestDto: Codable, Responseable, JSONEncodable, Hashable {

    public var inquiryReason: String?
    public var inquiryDesc: String?
    public var id: String?

    public init(inquiryReason: String? = nil, inquiryDesc: String? = nil, id: String? = nil) {
        self.inquiryReason = inquiryReason
        self.inquiryDesc = inquiryDesc
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inquiryReason
        case inquiryDesc
        case id
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        inquiryReason = container.decodeIfPresent(.inquiryReason)
        inquiryDesc = container.decodeIfPresent(.inquiryDesc)
        id = container.decodeIfPresent(.id)
       
    }
    
}

extension ValidateInquiryRequestDto: Emptyable {
    public static var empty: ValidateInquiryRequestDto {
        return .init(inquiryReason: nil, inquiryDesc: nil, id: nil)
    }
}
